name       : python-betamax
version    : 0.8.1
release    : 4
source     :
    - https://github.com/betamaxpy/betamax/archive/0.8.1.tar.gz : 69b4e14e36273211e5a392da5c9ed572dd8b0c446b35204f57dca81765ed2fc1
license    : Apache-2.0
component  : programming.python
summary    : A VCR imitation designed only for python-requests
description: |
    Betamax is a VCR imitation for requests. This will make mocking out requests much easier.
builddeps  :
    - python-pytest
    - python-requests
rundeps    :
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # tests require networking
#    %python3_test
